# Multiplication operations with numpy arrays

In [12]:
import numpy as np

In [13]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a * b
print("c =", c,"\n", "Type:", type(c), "\n", "Shape:", c.shape)

c = [ 4 10 18] 
 Type: <class 'numpy.ndarray'> 
 Shape: (3,)


In [14]:
c = np.multiply(a, b)
print("c =", c,"\n", "Type:", type(c), "\n", "Shape:", c.shape)

c = [ 4 10 18] 
 Type: <class 'numpy.ndarray'> 
 Shape: (3,)


In [15]:
c = np.dot(a, b)
print("c =", c,"\n", "Type:", type(c), "\n", "Shape:", c.shape)

c = np.dot(a, b.T)
print("c =", c,"\n", "Type:", type(c), "\n", "Shape:", c.shape)

c = np.dot(a.T, b)
print("c =", c,"\n", "Type:", type(c), "\n", "Shape:", c.shape)

c = 32 
 Type: <class 'numpy.int32'> 
 Shape: ()
c = 32 
 Type: <class 'numpy.int32'> 
 Shape: ()
c = 32 
 Type: <class 'numpy.int32'> 
 Shape: ()


In [16]:
np.random.seed(7)

a_matrix = np.random.randint(1, 11, size=(2, 3))
print("a_matrix =\n", a_matrix,"\n", "Type:", type(a_matrix), "\n", "Shape:", a_matrix.shape)

x = np.arange((3))
print("x =", x,"\n", "Type:", type(x), "\n", "Shape:", x.shape)


a_matrix =
 [[ 5 10  7]
 [ 4  4  8]] 
 Type: <class 'numpy.ndarray'> 
 Shape: (2, 3)
x = [0 1 2] 
 Type: <class 'numpy.ndarray'> 
 Shape: (3,)


In [17]:
result = a_matrix * x
print("result of (a_matrix * x) =\n", result,"\n", "Type:", type(result), "\n", "Shape:", result.shape)


result of (a_matrix * x) =
 [[ 0 10 14]
 [ 0  4 16]] 
 Type: <class 'numpy.ndarray'> 
 Shape: (2, 3)


In [18]:

result_colsum = np.sum(a_matrix * x, axis=1)
print("result of column sums of (a_matrix * x) =\n", result_colsum,"\n", "Type:", type(result_colsum), "\n", "Shape:", result_colsum.shape)


result of column sums of (a_matrix * x) =
 [24 20] 
 Type: <class 'numpy.ndarray'> 
 Shape: (2,)


In [19]:

result_rowsum = np.sum(a_matrix * x, axis=0)
print("result of row sums of (a_matrix * x) =\n", result_rowsum,"\n", "Type:", type(result_rowsum), "\n", "Shape:", result_rowsum.shape)


result of row sums of (a_matrix * x) =
 [ 0 14 30] 
 Type: <class 'numpy.ndarray'> 
 Shape: (3,)


In [20]:

result_totalsum = np.sum(a_matrix * x)
print("result of total sum of (a_matrix * x) =\n", result_totalsum,"\n", "Type:", type(result_totalsum), "\n", "Shape:", result_totalsum.shape)


result of total sum of (a_matrix * x) =
 44 
 Type: <class 'numpy.int32'> 
 Shape: ()


In [21]:

result_totalsum = np.sum(result_colsum)
print("result of total sum of matrix (a_matrix * x) by column sums =\n", result_totalsum,"\n", "Type:", type(result_totalsum), "\n", "Shape:", result_totalsum.shape)

result of total sum of matrix (a_matrix * x) by column sums =
 44 
 Type: <class 'numpy.int32'> 
 Shape: ()


In [22]:
result_totalsum = np.sum(result_rowsum)
print("result of total sum of matrix (a_matrix * x) by row sums =\n", result_totalsum,"\n", "Type:", type(result_totalsum), "\n", "Shape:", result_totalsum.shape)

result of total sum of matrix (a_matrix * x) by row sums =
 44 
 Type: <class 'numpy.int32'> 
 Shape: ()
